import type { WeeklyMenu } from '~~/layers/menu/shared/types/types';

export const menus: WeeklyMenu[] = [
  {
    id: 1,
    createdAt: '2023-10-01',
    updatedAt: '2023-10-01',
    startDate: '2023-10-01',
    endDate: '2023-10-07',
    name: 'Menú Semanal 1',
    type: 'std',
    isActive: true,
    days: [
      {
        id: 1,
        dayOfWeek: 'Lunes',
        breakfast: {
          id: 1,
          mainDish: { id: 101, name: 'Tortilla de huevo', calories: 300 },
          side1: { id: 201, name: 'Fruta de temporada', calories: 80 },
          side2: null,
          ramekin: { id: 301, name: 'Mermelada de fresa', calories: 50 },
          contenedor: 'Contenedor 1',
          image: '/tortilla-espinacas.jpeg',
          description:
            'Tortilla de espinacas con queso feta y tomate, acompañada de fruta de temporada y yogur natural.',
        },
        lunch: {
          id: 1,
          mainDish: { id: 102, name: 'Pechuga a la plancha', calories: 350 },
          side1: { id: 203, name: 'Ensalada de lechuga y tomate', calories: 70 },
          side2: { id: 204, name: 'Arroz integral', calories: 180 },
          ramekin: { id: 302, name: 'Aderezo de mostaza y miel', calories: 90 },
          contenedor: 'Contenedor 2',
          image: '/pechuga-plancha.jpeg',
          description: 'Pechuga a la plancha con ensalada de lechuga y tomate, acompañada de arroz integral.',
        },
        dinner: {
          id: 1,
          mainDish: { id: 103, name: 'Salmón al horno', calories: 400 },
          side1: { id: 205, name: 'Espárragos al vapor', calories: 60 },
          side2: { id: 206, name: 'Quinoa', calories: 170 },
          ramekin: { id: 303, name: 'Salsa de yogur y eneldo', calories: 50 },
          contenedor: 'Contenedor 3',
          image: '/salmón-horno.jpeg',
          description: 'Salmón al horno con espárragos al vapor y quinoa, acompañado de salsa de yogur y eneldo.',
        },
        snack1: {
          id: 1,
          mainDish: { id: 104, name: 'Barra de granola', calories: 150 },
          side1: { id: 207, name: 'Fruta de temporada', calories: 80 },
          side2: { id: 208, name: 'Nueces', calories: 100 },
          ramekin: { id: 304, name: 'Miel', calories: 60 },
          contenedor: 'Contenedor 4',
          image: '/barra-granola.jpeg',
          description: 'Barra de granola con fruta de temporada y nueces, acompañada de miel.',
        },
        snack2: {
          id: 1,
          mainDish: { id: 105, name: 'Batido de plátano y espinacas', calories: 200 },
          side1: { id: 209, name: 'Semillas de chía', calories: 90 },
          side2: { id: 210, name: 'Leche de almendras', calories: 70 },
          ramekin: { id: 305, name: 'Proteína en polvo', calories: 110 },
          contenedor: 'Contenedor 5',
          image: '/batido-espinacas.jpeg',
          description:
            'Batido de plátano y espinacas con semillas de chía y leche de almendras, acompañado de proteína en polvo.',
        },
      },
      {
        id: 2,
        dayOfWeek: 'Martes',
        breakfast: {
          id: 2,
          mainDish: { id: 106, name: 'Tostadas de aguacate', calories: 320 },
          side1: { id: 211, name: 'Huevo pochado', calories: 140 },
          side2: { id: 212, name: 'Fruta de temporada', calories: 80 },
          ramekin: { id: 306, name: 'Salsa picante', calories: 20 },
          contenedor: 'Contenedor 1',
          image: '/tostadas-aguacate.jpeg',
          description: 'Tostadas de aguacate con huevo pochado y fruta de temporada, acompañadas de salsa picante.',
        },
        lunch: {
          id: 2,
          mainDish: { id: 107, name: 'Ensalada César con pollo', calories: 400 },
          side1: { id: 213, name: 'Crutones', calories: 90 },
          side2: { id: 214, name: 'Queso parmesano', calories: 120 },
          ramekin: { id: 307, name: 'Aderezo César', calories: 100 },
          contenedor: 'Contenedor 2',
          image: '/ensalada-cesar.jpeg',
          description: 'Ensalada César con pollo, crutones y queso parmesano, acompañada de aderezo César.',
        },
        dinner: {
          id: 2,
          mainDish: { id: 108, name: 'Pasta integral con verduras salteadas', calories: 420 },
          side1: { id: 215, name: 'Aceitunas negras', calories: 60 },
          side2: { id: 216, name: 'Parmesano rallado', calories: 100 },
          ramekin: { id: 308, name: 'Aceite de oliva virgen extra', calories: 80 },
          contenedor: 'Contenedor 3',
          image: '/pasta-verduras.jpeg',
          description:
            'Pasta integral con verduras salteadas, aceitunas negras y parmesano rallado, acompañada de aceite de oliva virgen extra.',
        },
        snack1: {
          id: 2,
          mainDish: { id: 109, name: 'Yogur griego con miel y nueces', calories: 200 },
          side1: { id: 0, name: '', calories: 0 },
          side2: { id: 0, name: '', calories: 0 },
          ramekin: { id: 0, name: '', calories: 0 },
          contenedor: 'Contenedor 4',
          image: '/yogur-griego.jpeg',
          description: 'Yogur griego con miel y nueces.',
        },
        snack2: {
          id: 2,
          mainDish: { id: 110, name: 'Palitos de zanahoria y apio con hummus', calories: 160 },
          side1: { id: 0, name: '', calories: 0 },
          side2: { id: 0, name: '', calories: 0 },
          ramekin: { id: 0, name: '', calories: 0 },
          contenedor: 'Contenedor 5',
          image: '/palitos-zanahoria.jpeg',
          description: 'Palitos de zanahoria y apio con hummus.',
        },
      },
    ],
  },
  {
    id: 2,
    createdAt: '2023-10-01',
    updatedAt: '2023-10-01',
    startDate: '2023-10-01',
    endDate: '2023-10-07',
    name: 'Menú Semanal 1',
    type: 'veg',
    isActive: true,
    days: [
      {
        id: 1,
        dayOfWeek: 'Lunes',
        breakfast: {
          id: 1,
          mainDish: { id: 101, name: 'Tortilla de espinacas', calories: 300 },
          side1: { id: 201, name: 'Fruta de temporada', calories: 80 },
          side2: null,
          ramekin: { id: 301, name: 'Mermelada de fresa', calories: 50 },
          contenedor: 'Contenedor 1',
          image: '/tortilla-espinacas.jpeg',
          description:
            'Tortilla de espinacas con queso feta y tomate, acompañada de fruta de temporada y yogur natural.',
        },
        lunch: {
          id: 1,
          mainDish: { id: 102, name: 'Portobello asado', calories: 350 },
          side1: { id: 203, name: 'Ensalada de lechuga y tomate', calories: 70 },
          side2: { id: 204, name: 'Quinoa', calories: 180 },
          ramekin: { id: 302, name: 'Aderezo de mostaza y miel', calories: 90 },
          contenedor: 'Contenedor 2',
          image: '/pechuga-plancha.jpeg',
          description: 'Pechuga a la plancha con ensalada de lechuga y tomate, acompañada de arroz integral.',
        },
        dinner: {
          id: 1,
          mainDish: { id: 103, name: 'Salmón al horno', calories: 400 },
          side1: { id: 205, name: 'Espárragos al vapor', calories: 60 },
          side2: { id: 206, name: 'Quinoa', calories: 170 },
          ramekin: { id: 303, name: 'Salsa de yogur y eneldo', calories: 50 },
          contenedor: 'Contenedor 3',
          image: '/salmón-horno.jpeg',
          description: 'Salmón al horno con espárragos al vapor y quinoa, acompañado de salsa de yogur y eneldo.',
        },
        snack1: {
          id: 1,
          mainDish: { id: 104, name: 'Barra de granola', calories: 150 },
          side1: { id: 207, name: 'Fruta de temporada', calories: 80 },
          side2: { id: 208, name: 'Nueces', calories: 100 },
          ramekin: { id: 304, name: 'Miel', calories: 60 },
          contenedor: 'Contenedor 4',
          image: '/barra-granola.jpeg',
          description: 'Barra de granola con fruta de temporada y nueces, acompañada de miel.',
        },
        snack2: {
          id: 1,
          mainDish: { id: 105, name: 'Batido de plátano y espinacas', calories: 200 },
          side1: { id: 209, name: 'Semillas de chía', calories: 90 },
          side2: { id: 210, name: 'Leche de almendras', calories: 70 },
          ramekin: { id: 305, name: 'Proteína en polvo', calories: 110 },
          contenedor: 'Contenedor 5',
          image: '/batido-espinacas.jpeg',
          description:
            'Batido de plátano y espinacas con semillas de chía y leche de almendras, acompañado de proteína en polvo.',
        },
      },
      {
        id: 2,
        dayOfWeek: 'Martes',
        breakfast: {
          id: 2,
          mainDish: { id: 106, name: 'Tostadas de aguacate', calories: 320 },
          side1: { id: 211, name: 'Huevo pochado', calories: 140 },
          side2: { id: 212, name: 'Fruta de temporada', calories: 80 },
          ramekin: { id: 306, name: 'Salsa picante', calories: 20 },
          contenedor: 'Contenedor 1',
          image: '/tostadas-aguacate.jpeg',
          description: 'Tostadas de aguacate con huevo pochado y fruta de temporada, acompañadas de salsa picante.',
        },
        lunch: {
          id: 2,
          mainDish: { id: 107, name: 'Ensalada César con pollo', calories: 400 },
          side1: { id: 213, name: 'Crutones', calories: 90 },
          side2: { id: 214, name: 'Queso parmesano', calories: 120 },
          ramekin: { id: 307, name: 'Aderezo César', calories: 100 },
          contenedor: 'Contenedor 2',
          image: '/ensalada-cesar.jpeg',
          description: 'Ensalada César con pollo, crutones y queso parmesano, acompañada de aderezo César.',
        },
        dinner: {
          id: 2,
          mainDish: { id: 108, name: 'Pasta integral con verduras salteadas', calories: 420 },
          side1: { id: 215, name: 'Aceitunas negras', calories: 60 },
          side2: { id: 216, name: 'Parmesano rallado', calories: 100 },
          ramekin: { id: 308, name: 'Aceite de oliva virgen extra', calories: 80 },
          contenedor: 'Contenedor 3',
          image: '/pasta-verduras.jpeg',
          description:
            'Pasta integral con verduras salteadas, aceitunas negras y parmesano rallado, acompañada de aceite de oliva virgen extra.',
        },
        snack1: {
          id: 2,
          mainDish: { id: 109, name: 'Yogur griego con miel y nueces', calories: 200 },
          side1: { id: 0, name: '', calories: 0 },
          side2: { id: 0, name: '', calories: 0 },
          ramekin: { id: 0, name: '', calories: 0 },
          contenedor: 'Contenedor 4',
          image: '/yogur-griego.jpeg',
          description: 'Yogur griego con miel y nueces.',
        },
        snack2: {
          id: 2,
          mainDish: { id: 110, name: 'Palitos de zanahoria y apio con hummus', calories: 160 },
          side1: { id: 0, name: '', calories: 0 },
          side2: { id: 0, name: '', calories: 0 },
          ramekin: { id: 0, name: '', calories: 0 },
          contenedor: 'Contenedor 5',
          image: '/palitos-zanahoria.jpeg',
          description: 'Palitos de zanahoria y apio con hummus.',
        },
      },
    ],
  },
];
